// <auto-generated />
using System;
using DevIO.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevIO.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20200330145724_CreateInitial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevIO.Business.Models.Adicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TempoAdicional");

                    b.Property<decimal>("ValorAdicional");

                    b.HasKey("Id");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("DevIO.Business.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SaborPedidoId");

                    b.Property<int?>("TamanhoPedidoId");

                    b.Property<int>("TempoTotalParaPreparo");

                    b.Property<decimal>("ValorTotalDoPedido");

                    b.HasKey("Id");

                    b.HasIndex("SaborPedidoId");

                    b.HasIndex("TamanhoPedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("DevIO.Business.Models.PedidoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdicionalId");

                    b.Property<int>("PedidoId");

                    b.HasKey("Id");

                    b.HasIndex("AdicionalId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoAdicionais");
                });

            modelBuilder.Entity("DevIO.Business.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TempoAdicional");

                    b.Property<decimal>("ValorAdicional");

                    b.HasKey("Id");

                    b.ToTable("Sabores");
                });

            modelBuilder.Entity("DevIO.Business.Models.Tamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TempoAdicional");

                    b.Property<decimal>("ValorAdicional");

                    b.HasKey("Id");

                    b.ToTable("Tamanhos");
                });

            modelBuilder.Entity("DevIO.Business.Models.Pedido", b =>
                {
                    b.HasOne("DevIO.Business.Models.Sabor", "SaborPedido")
                        .WithMany()
                        .HasForeignKey("SaborPedidoId");

                    b.HasOne("DevIO.Business.Models.Tamanho", "TamanhoPedido")
                        .WithMany()
                        .HasForeignKey("TamanhoPedidoId");
                });

            modelBuilder.Entity("DevIO.Business.Models.PedidoAdicional", b =>
                {
                    b.HasOne("DevIO.Business.Models.Adicional", "Adicional")
                        .WithMany("PedidoAdicionais")
                        .HasForeignKey("AdicionalId");

                    b.HasOne("DevIO.Business.Models.Pedido", "Pedido")
                        .WithMany("PedidoAdicionais")
                        .HasForeignKey("PedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
